[package]
name = "aya-log-parser"
version = "0.1.11-dev.0"
description = "A parser for the aya log format strings"
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
edition.workspace = true

[dependencies]
aya-log-common = { workspace = true }

[lib]
path = "src/lib.rs"
