[package]
name = "aya-log-ebpf-macros"
version = "0.1.0"
description = "Proc macros used by aya-log-ebpf"
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
edition.workspace = true

[dependencies]
aya-log-common = { workspace = true }
aya-log-parser = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }

[lib]
proc-macro = true
