name: lint

on:
  push:
    branches:
      - main
      - ci

  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rustfmt, clippy, miri, rust-src

      - uses: Swatinem/rust-cache@v2

      - run: cargo install taplo-cli
      - run: taplo fmt --check

      - name: Check formatting
        run: cargo fmt --all -- --check

      - uses: taiki-e/install-action@cargo-hack
      - name: Run clippy
        run: cargo hack clippy --all-targets --feature-powerset --workspace -- --deny warnings

      - name: Run miri
        run: |
          cargo hack miri test --all-targets --feature-powerset \
            --exclude aya-bpf \
            --exclude aya-bpf-bindings \
            --exclude aya-log-ebpf \
            --exclude integration-ebpf \
            --exclude integration-test \
            --workspace
